name: Deploy to GitHub Pages

on:
  push:
    branches: [ dev ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/dev'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./Prototype
        publish_branch: gh-pages
        force_orphan: true
        commit_message: Deploy from dev branch ${{ github.sha }}